config/routes.rb
require 'sidekiq/web'

Spotxm::Application.routes.draw do
 	devise_for :users

    resources :channels, only: [:index, :show]    
    resources :tracks, only: :index
    match 'now_playing', :controller => 'channels', :action => 'now_playing'
    root to: 'tracks#search'
    
    constraint = lambda { |request| request.env["warden"].authenticate? and request.env['warden'].user.admin? }
	constraints constraint do
    	mount Sidekiq::Web => '/sidekiq'
    end
end

app/views/layouts/_channel_search.html.slim
= form_for :channel, method: :get do |channel_form|
	= channel_form.label :channel_params, "Search for a channel"
	= channel_form.text_field :channel_params, :id => "channel-search", :placeholder => "Enter a channel number"
	= channel_form.submit 'Find Channel'

app/views/layouts/_navbar.html.slim
div class="navbar navbar-inverse navbar-fixed-top"
	div.navbar-inner
		div.container
			a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse"
				span.icon-bar
				span.icon-bar
				span.icon-bar
			= link_to "Spot XM", root_path, :class => "brand"
			div class="nav-collapse collapse"
				ul.nav
					li.active
						= link_to "Home", root_path
					
					li
						= link_to "Channels", channels_path
					li
						= link_to "About", "#"

app/views/layouts/_search.html.slim
div.well
	= simple_form_for :search, :url => tracks_path, method: :get do |search_form| 
		= search_form.label :search_params, "Search for a track or channel"
		= search_form.text_field :search_params, :id => "search", :placeholder => @search_params || "Enter your search term"
		div id="search_start_time" class="input-append"
			= search_form.input :start_time, input_html: { "data-format" =>"MM/dd/yyyy HH:mm:ss PP",  "type" => "text" }
			span.add-on
				i data-time-icon="icon-time" data-date-icon="icon-calendar"
		div id="search_end_time" class="input-append"
			= search_form.input :end_time, input_html: { "data-format" =>"MM/dd/yyyy HH:mm:ss PP",  "type" => "text" }
			span.add-on
				i data-time-icon="icon-time" data-date-icon="icon-calendar"
		= search_form.submit 'Find'

app/views/layouts/application.html.slim
doctype html
html
	head
		title SpotXM
		= stylesheet_link_tag "application", :media => "all"
		= javascript_include_tag "application"
		= csrf_meta_tags

	body
		div.container
			h1 = link_to "SpotXM", root_path
			p#about-service Wondering what's played on Sirius XM?  You're in the right place.

			= render "layouts/search"

			- if alert
				p.alert = alert
			- if notice
				p.notice = notice

			= yield